package dev.androidemu

import kotlin.math.PI
import kotlin.math.cos
import kotlin.math.pow
import kotlin.math.roundToInt
import kotlin.math.sin

/**
 * What the framebuffer's 64 indices mean in colour.
 *
 * The 2C02 never emitted red, green and blue. It emitted a square wave: a two-bit
 * *level* set the two voltages it switched between, and a four-bit *hue* set the
 * phase at which it switched. A television decoded that the same way it decoded
 * anything else. So rather than paste in tables of numbers nobody can check,
 * these are generated by doing what the chip did and then decoding it — which
 * means the knobs below are the ones a television actually had.
 *
 * The model is checked against the table the core ships in `PaletteTest`: it
 * lands within about 9 of 255 per channel, comfortably inside the spread between
 * any two published NES palettes.
 */
object PaletteModel {
    /** The two voltages the chip switches between, per level, low then high. */
    private val LOW = doubleArrayOf(0.350, 0.518, 0.962, 1.550)
    private val HIGH = doubleArrayOf(1.094, 1.506, 1.962, 1.962)
    private val BLACK = LOW[1]
    private val WHITE = HIGH[3]

    /**
     * Where the colour wheel starts. Four twelfths, which is what lines the model
     * up with every published palette — the phase a television's burst locked to.
     */
    private const val BURST = 4.0

    /** One colour cycle is twelve samples of the square wave. */
    private const val SAMPLES = 12

    private fun signal(hue: Int, level: Int, sample: Int): Double = when {
        // Hue 0 holds the high voltage all cycle, which is why it is a grey.
        hue == 0 -> HIGH[level]
        // $xD holds the low voltage for its own level: grey at the top two
        // levels, and below black — so clamped to it — at the bottom two.
        hue == 13 -> LOW[level]
        // $xE and $xF are blanking. Always black.
        hue >= 14 -> LOW[1]
        else -> if ((sample + hue) % SAMPLES < SAMPLES / 2) HIGH[level] else LOW[level]
    }

    /**
     * Builds the 64 colours, as 0xRRGGBB.
     *
     * [saturation] scales the colour carried against the brightness, the way a
     * television's colour control did. [tint] turns the wheel, in twelfths of a
     * cycle, the way its tint control did. [contrast] and [brightness] act on
     * brightness alone, and [gamma] bends the response of the glass.
     */
    fun build(
        saturation: Double = 1.0,
        tint: Double = 0.0,
        contrast: Double = 1.0,
        brightness: Double = 0.0,
        gamma: Double = 1.0,
    ): IntArray = IntArray(64) { index ->
        val hue = index and 15
        val level = (index shr 4) and 3
        var y = 0.0
        var i = 0.0
        var q = 0.0
        for (sample in 0 until SAMPLES) {
            val volts = (signal(hue, level, sample) - BLACK) / (WHITE - BLACK)
            val angle = 2.0 * PI * (sample + BURST + tint) / SAMPLES
            y += volts
            i += volts * cos(angle)
            q += volts * sin(angle)
        }
        y = y / SAMPLES * contrast + brightness
        i = i / SAMPLES * saturation * 2.0
        q = q / SAMPLES * saturation * 2.0
        rgb(
            y + 0.956 * i + 0.619 * q,
            y - 0.272 * i - 0.647 * q,
            y - 1.106 * i + 1.703 * q,
            gamma,
        )
    }

    private fun rgb(r: Double, g: Double, b: Double, gamma: Double): Int {
        fun channel(v: Double): Int =
            (255.0 * v.coerceIn(0.0, 1.0).pow(gamma)).roundToInt().coerceIn(0, 255)
        return (channel(r) shl 16) or (channel(g) shl 8) or channel(b)
    }

    /**
     * The model's closest match to the table the core ships, for the places on
     * this side that need actual colours rather than "whatever the core uses" —
     * the built preview pattern, mostly. These two numbers are what `PaletteTest`
     * pins: they bring the model within about 9 of 255 per channel of that table.
     */
    fun standard(): IntArray = build(saturation = 0.90)

    /** The 192 bytes the core wants: 64 colours, red green blue. */
    fun bytes(colours: IntArray): ByteArray {
        val out = ByteArray(colours.size * 3)
        for ((at, colour) in colours.withIndex()) {
            out[at * 3] = (colour shr 16).toByte()
            out[at * 3 + 1] = (colour shr 8).toByte()
            out[at * 3 + 2] = colour.toByte()
        }
        return out
    }

    /**
     * Reads a 192-byte `.pal` file, the format every palette on the internet is
     * published in. Longer files carry the emphasis variants after the first 64
     * colours; those are ignored until the core encodes emphasis at all.
     */
    fun parse(file: ByteArray): IntArray? {
        if (file.size < 64 * 3) return null
        return IntArray(64) { at ->
            ((file[at * 3].toInt() and 255) shl 16) or
                ((file[at * 3 + 1].toInt() and 255) shl 8) or
                (file[at * 3 + 2].toInt() and 255)
        }
    }
}

/**
 * The colour sets on offer. Plain names, because the choice is "which of these
 * looks right to you" and not "which decoder matrix do you prefer".
 *
 * [id] is persisted, so a retired one is never reused — the same rule [Filter]
 * follows and for the same reason.
 */
enum class Palette(val id: Int, val label: String, val note: String) {
    /**
     * What the core paints with when nothing has been chosen. Left as the core's
     * own table rather than regenerated, so upgrading never quietly restains a
     * picture somebody was happy with.
     */
    Standard(0, "Standard", "The colours the app has always used"),
    Hardware(1, "Hardware", "Decoded from what the chip actually emitted, nothing added"),
    Soft(2, "Soft", "Gentler colour, the way a television left at the factory setting looked"),
    Vivid(3, "Vivid", "Colour turned up, the way most people ran theirs"),
    // 4 was "Cool", a tint drift. Cut: eighteen degrees of hue is enough to turn
    // a red cap magenta, which reads as a fault rather than as a choice, and a
    // smaller shift was not worth a slot. The id stays retired.
    File(5, "From a file", "A .pal palette you imported");

    /** The table, or null for [Standard], which is the core's own. */
    fun colours(): IntArray? = when (this) {
        Standard -> null
        Hardware -> PaletteModel.build()
        Soft -> PaletteModel.build(saturation = 0.78, contrast = 0.96, brightness = 0.02, gamma = 1.06)
        Vivid -> PaletteModel.build(saturation = 1.30, contrast = 1.05, gamma = 0.94)
        // Supplied at run time; the caller substitutes the imported table.
        File -> null
    }

    companion object {
        fun of(id: Int) = entries.firstOrNull { it.id == id } ?: Standard
    }
}
