#!/usr/bin/env python3
"""Promote one concept into the app. Everything it writes is derived, never drawn.

  python3 brand/tools/apply.py c-one-in-four

Run `build.py` first: this copies what `brand/android/<slug>/` already holds
rather than re-deriving geometry, so the drawable that ships is a copy of the
file that was reviewed and measured, not a second rendering of the same idea
that can drift from it.

Whatever it overwrites is kept in `brand/previous/`, once, on the first run.

## The three kinds of surface

The sibling Controlplaine project learned this the expensive way, so it is
written down here before there is anything to discover: a mark lands on more
surfaces than a generator regenerates, and the ones it does not are stale from
the moment the mark changes unless somebody knows they exist.

  GENERATED   this script writes the file; change the mark, re-run, done.
  REFERENCE   the file points at generated art by name; it follows for free.
  REDRAWN     drawn for the surface it sits on. Re-running does NOT update it.

Emulia currently has five generated, one reference and none redrawn. Keep that
table honest -- a redrawn surface with nobody tracking it is the defect.
"""

import shutil
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REPO = ROOT.parent
RES = REPO / "android" / "app" / "src" / "main" / "res"
MANIFEST = REPO / "android" / "app" / "src" / "main" / "AndroidManifest.xml"
PREVIOUS = ROOT / "previous"
# Written after the first successful promotion. Its presence is what says the
# app already wears a generated mark, so a later run has nothing to preserve.
PROMOTED = PREVIOUS / ".promoted"
AND = "{http://schemas.android.com/apk/res/android}"

# The in-app mark's tile, as a path. A drawable has no `currentColor` and
# `android:tint` would paint every path in it one colour, headset and all -- so
# the small master carries its OWN rounded ground and reads on a light panel and
# a dark one without asking the theme anything.
TILE_R = 24.0


def rounded_rect(size=108.0, r=TILE_R):
    s, k = size, r
    return ("M%g,0 h%g a%g,%g 0 0 1 %g,%g v%g a%g,%g 0 0 1 %g,%g "
            "h%g a%g,%g 0 0 1 %g,%g v%g a%g,%g 0 0 1 %g,%g Z") % (
        k, s - 2 * k, k, k, k, k, s - 2 * k, k, k, -k, k,
        -(s - 2 * k), k, k, -k, -k, -(s - 2 * k), k, k, k, -k)


def inner_xml(path):
    """A generated vector's children, as a string, minus its <vector> wrapper."""
    ET.register_namespace("android", AND[1:-1])
    ET.register_namespace("aapt", "http://schemas.android.com/aapt")
    root = ET.parse(path).getroot()
    return "".join(ET.tostring(c, encoding="unicode") for c in root)


def small_master(slug):
    """The in-app mark: the adaptive art, clipped to its own rounded tile.

    Composed from the two generated layers rather than authored, for the same
    reason everything else here is a copy: a hand-kept second version of the
    mark is a REDRAWN surface pretending to be a GENERATED one, and it goes
    stale silently.
    """
    src = ROOT / "android" / slug / "drawable"
    body = inner_xml(src / "ic_launcher_background.xml") + \
        inner_xml(src / "ic_launcher_foreground.xml")
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- GENERATED by brand/tools/apply.py from the %s adaptive layers\n'
        '     - do not hand-edit. Regenerate: python3 brand/tools/apply.py %s\n\n'
        '     The launcher art carrying its own rounded ground, for use inside\n'
        '     the app where there is no adaptive-icon machinery and no mask. -->\n'
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    xmlns:aapt="http://schemas.android.com/aapt"\n'
        '    android:width="108dp" android:height="108dp"\n'
        '    android:viewportWidth="108" android:viewportHeight="108">\n'
        '  <group>\n'
        '    <clip-path android:pathData="%s"/>\n'
        '    %s\n'
        '  </group>\n'
        '</vector>\n' % (slug, slug, rounded_rect(), body))


def keep_previous(dest: Path):
    """Back up an existing file, but only on the very first promotion.

    `previous/` is for what the mark REPLACED. A re-run -- after a tweak, or to
    flip a flag -- would otherwise file the current mark in there as its own
    predecessor, which is worse than filing nothing because it reads as history
    and is not. The first version of this guard skipped files carrying the
    generator's banner, which is invisible in a PNG; ten launcher bitmaps went
    into `previous/` as their own ancestors before the marker replaced it.
    """
    if PROMOTED.exists() or not dest.exists():
        return
    rel = dest.relative_to(REPO)
    keep = PREVIOUS / rel
    if keep.exists():
        return
    keep.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(dest, keep)
    print("  kept  %s" % keep.relative_to(REPO))


def place(src: Path, dest: Path):
    dest.parent.mkdir(parents=True, exist_ok=True)
    keep_previous(dest)
    shutil.copy2(src, dest)
    print("  ->    %s" % dest.relative_to(REPO))


def main():
    if len(sys.argv) != 2:
        slugs = sorted(p.name for p in (ROOT / "concepts").iterdir() if p.is_dir())
        sys.exit("usage: apply.py <slug>\n  " + "\n  ".join(slugs))
    slug = sys.argv[1]
    src = ROOT / "android" / slug
    if not src.is_dir():
        sys.exit("no built art for %s - run build.py first" % slug)

    print("Promoting %s\n" % slug)
    print("GENERATED")
    for f in sorted(src.rglob("*")):
        if f.is_file():
            place(f, RES / f.relative_to(src))

    mark = RES / "drawable" / "ic_emulia_mark.xml"
    keep_previous(mark)
    mark.parent.mkdir(parents=True, exist_ok=True)
    mark.write_text(small_master(slug))
    print("  ->    %s" % mark.relative_to(REPO))

    # The placeholder this replaces. It was a single flat drawable referenced
    # straight from the manifest; the adaptive icon supersedes it entirely, and
    # leaving it behind means two icons in the tree and no way to tell which one
    # a surface is using.
    old = RES / "drawable" / "ic_launcher.xml"
    if old.exists():
        keep_previous(old)
        old.unlink()
        print("  rm    %s (placeholder, superseded by the adaptive icon)"
              % old.relative_to(REPO))

    print("\nREFERENCE")
    text = MANIFEST.read_text()
    before = text
    # @mipmap, not @drawable: mipmap resources survive density stripping, and
    # the anydpi-v26 alias is what makes a launcher use the adaptive icon at all.
    text = text.replace('android:icon="@drawable/ic_launcher"',
                        'android:icon="@mipmap/ic_launcher" '
                        'android:roundIcon="@mipmap/ic_launcher_round"')
    if text != before:
        keep_previous(MANIFEST)
        MANIFEST.write_text(text)
        print("  ->    %s (icon + roundIcon -> @mipmap)"
              % MANIFEST.relative_to(REPO))
    else:
        print("  ok    %s already points at @mipmap"
              % MANIFEST.relative_to(REPO))

    if not PROMOTED.exists():
        PREVIOUS.mkdir(parents=True, exist_ok=True)
        PROMOTED.write_text(
            "%s promoted first; brand/previous/ holds what it replaced.\n" % slug)

    print("""
REDRAWN
  none. Nothing in this app is drawn per-surface yet, which is the state to
  keep: every mark below follows from the files above.

    launcher, adaptive        res/mipmap-anydpi-v26/ic_launcher{,_round}.xml
    launcher, legacy bitmaps  res/mipmap-*dpi/ic_launcher{,_round}.png
    themed icon (Android 13)  res/drawable/ic_launcher_monochrome.xml
                              built, but NOT offered - see OFFER_MONOCHROME
    in-app mark               res/drawable/ic_emulia_mark.xml
    cold-start splash         res/values-v31/styles.xml (references the above)

Re-run build.py then apply.py after any change to brand/concepts/.""")


if __name__ == "__main__":
    main()
