// @generated by scripts/build-header-db.py — do not edit by hand.
//
// Header corrections keyed by ROM identity, sorted by identity so `lookup` can
// binary-search. Included by fixup.rs rather than compiled as its own module,
// because it is data rather than code.
//
// It is empty, and that is the correct default. An entry here overrides what a
// ROM says about itself, so a row nobody has verified against a real dump would
// silently mis-configure a real game — worse than leaving the header alone.
//
// To fill it in, point the generator at ROMs you have and a published board
// database; it emits a row only where the database and the ROM's own header
// disagree, and never guesses:
//
//     python3 scripts/build-header-db.py --roms ~/roms --db nescartdb.xml
//
// See docs/HEADER-DATABASE.md.

pub const TABLE: &[Override] = &[];
